### PR TITLE
Add Action that runs tests

### PR DESCRIPTION
**Pull request by palewire**

### CODE REVIEW

**Comment by palewire** [comment]
Added a linter and a matrix of node versions. I'll leave it alone now.

**Review by hobbes7878 — APPROVED** [review]
I, too, am a multiple follow-on commits after PR kinda guy. 

Looks good to me, man. 

Does the artifact upload presage a direct release to npm or are there other things the built files are useful for in the after-work?

**Comment by palewire** [comment]
It just uploads the zip. The automatic release to npm is next on my list after this one.

**Comment by hobbes7878** [comment]
I was hoping you'd say that. Added a secret on the org for ya: `NPM_TOKEN`

**Pull request merged**
